lesson3.currencies.*:
  type: config_entity
  label: 'Currencies config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
    currency:
      type: string
      lable: 'Currency name'
    code:
      type: string
      lable: 'Currency code'
    in_block:
      type: boolean
      lable: 'Display in block'
    on_page:
      type: boolean
      lable: 'Display on currencies page'